### PR TITLE
Complete solvers for ajd

### PR DESCRIPTION
**Pull request by qbarthelemy**
Complete solvers for ajd, adding `uwedge` (not ortho constraint) and `jade` (only ortho constraint) from pyRiemann

### CODE REVIEW

**Comment by tomMoral** [comment]
Nice! Do you have plots to share so we can take a look at the result on a simple case?

**Review by tomMoral — APPROVED** [review]
LGTM!

**Review by agramfort — APPROVED** [review]
Nice 👍

**Comment by agramfort** [comment]
@qbarthelemy can you share a screenshot of results ?

**Comment by qbarthelemy** [comment]
Results for `ortho=false`:
ortho_false

Results for `ortho=true`:
ortho_true

**Comment by agramfort** [comment]
That’s weird no ? Do you see also these failure modes with a very simple problem?

**Comment by qbarthelemy** [comment]
A simpler problem, with n_matrices=10, n_features=3:
ortho_false_simple
We observe the same (weird) trends, with `qndiag` still flat.
However, it is independent of the code proposed in my PR.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @qbarthelemy 🙏 

there is definitely something to understand / tweak in qndiag though.

**Pull request merged**
